### ISSUE TITLE
The latest runelite update(2024-05-23) broke this plugin

### ISSUE THREAD

**Issue by filipmunteanu** [DStatIO/StatusSocket#12]
There were a number of API changes and the plugin does not work anymore

**Comment by filipmunteanu** [comment]
I think the issue might be related to those functions being removed
client.getCameraX2()
client.getCameraY2()
client.getCameraZ2()

**Comment by DStatIO** [comment]
I'm not well versed in coding runelite plugins really anymore. If you could submit a pull request with needed changes to get it fixed I can have it updated.

**Comment by adrotter** [comment]
remove line 234, 235, 236 in main/java/com/statussocket/data/player/PlayerDataBuilder.java should do it

**Comment by Bazaar1** [comment]
Happy to do it if you make me a collaborator

**Comment by Bazaar1** [comment]
PR: https://github.com/DStatIO/StatusSocket/pull/13/commits/7eee9db5e7e4b6a31e147683aacd89bef01ca6a7

**Comment by DStatIO** [comment]
Pushed changes and submited for update
